import { DamagedPartType, SelectPair } from "../types/new-claim.types";

export const defaultClaimPolicyData = {
  policy_number: "AB-12345789",
  effect_date: "01/01/2022",
  expiration_date: "31/12/2022",
  owner: {
    natural_person: {
      id: 1,
      name: "Mario",
      lastname: "Rossi",
      fiscal_code: "RSSMRA73L09Z103F",
      province_of_residence: "Milano",
      city_of_residence: "Rho",
    },
  },
  contractor: {
    giuridical_person: {
      id: 2,
      business_name: "Acme Inc.",
      iva: "01960170684",
      registered_office_province: "Bologna",
      registered_office_city: "Bologna",
    },
  },
  ownerVehicle: {
    type: "A",
    plate: {
      number: "AB123CD",
      format: "Targa Italiana",
    },
  },
  damagedParts: [
    {
      pdNumber: "1669798161516",
      subject: {
        natural_person: {
          id: 1,
          name: "Mario",
          lastname: "Rossi",
          fiscal_code: "RSSMRA73L09Z103F",
          province_of_residence: "Milano",
          city_of_residence: "Rho",
        },
      },
      roleType: "CP",
      damages: [
        {
          damageType: "Vehicle",
          details: {
            plate: "AB123CD",
            format: "Targa Italiana",
            type: "A",
            collisionPoints: ["11"],
            note: "",
          },
        },
        {
          damageType: "Person",
          details: {
            personWoundedPoints: ["front_trunc", "rear_trunc"],
          },
        },
        {
          damageType: "Thing",
          details: {
            note: "gameboy",
          },
        },
      ],
      note: "Sedia",
    } as DamagedPartType,
    {
      pdNumber: "1669909946930",
      subject: {
        id: 1,
        name: "Luigi",
        lastname: "Verdi",
        fiscal_code: "VRDMRA73L09Z103F",
        province_of_residence: "Bologna",
        city_of_residence: "Bologna",
      },
      roleType: "TN",
      damages: [
        {
          damageType: "Person",
          details: {
            personWoundedPoints: ["front_head", "rear_head"],
          },
        },
        {
          damageType: "Thing",
          details: {
            note: "Notebook",
          },
        },
      ],
    } as DamagedPartType,
    {
      pdNumber: "1669909992417",
      subject: {
        id: 1,
        name: "Alice",
        lastname: "Cooper",
        fiscal_code: "CPPR73L09Z103F",
        province_of_residence: "Genova",
        city_of_residence: "Genova",
      },
      roleType: "TS",
      damages: [
        {
          damageType: "Thing",
          details: {
            note: "Sedia",
          },
        },
      ],
    } as DamagedPartType,
  ],
};

export const insuranceCodes: SelectPair[] = [
  { label: "ACCELERANT INSURANCE EUROPE SA N.V. *", value: "673" },
  { label: "ACCREDITED INSURANCE (EUROPE) LIMITED *", value: "672" },
  { label: "ADMIRAL EUROPE COMPAÑÍA DE SEGUROS SA", value: "911" },
  { label: "ADRIATIC OSIGURANJE D.D.", value: "667" },
  { label: "AFI ESCA IARD *", value: "609" },
  { label: "AFI ESCA SA *", value: "612" },
  { label: "AIG EUROPE SA", value: "344" },
  { label: "AIOI NISSAY DOWA INS. CO. OF EUROPE SE", value: "872" },
  { label: "ALLEANZA ASSICURAZIONI S.p.A.", value: "484" },
  { label: "ALLIANZ DIRECT Società per Azioni", value: "139" },
  { label: "ALLIANZ GLOBAL CORPORATE & SPECIALTY *", value: "880" },
  { label: "ALLIANZ GLOBAL LIFE DAC *", value: "884" },
  { label: "ALLIANZ LEBENSVERSICHERUNGS AG *", value: "660" },
  { label: "ALLIANZ Società per Azioni", value: "3" },
  { label: "ALLIANZ VIVA S.p.A.", value: "352" },
  { label: "AMTRUST ASSICURAZIONI S.p.A.", value: "471" },
  { label: "AMTRUST INTERNATIONAL UNDERWRITERS DAC *", value: "610" },
  { label: "ARAG SE Rappresentanza Generale e Direzione per l'Italia", value: "616" },
  { label: "ARCA ASSICURAZIONI S.p.A. *", value: "417" },
  { label: "ARCA VITA S.p.A. *", value: "341" },
  { label: "ARCH INSURANCE (EU) DAC *", value: "666" },
  { label: "ARGOGLOBAL ASSICURAZIONI S.p.A.", value: "469" },
  { label: "ASISA ASISTENCIA SANITARIA INTERPROVINCIAL DE SEGUROS SA *", value: "644" },
  { label: "ASSICURATRICE MILANESE S.p.A.", value: "327" },
  { label: "ASSICURATRICE VAL PIAVE S.p.A.", value: "85" },
  { label: "ASSICURAZIONI GENERALI S.p.A.", value: "483" },
  { label: "ASSICURAZIONI RISCHI AGRICOLI VMG 1857 S.p.A.", value: "45" },
  { label: "ASSIMOCO S.p.A.", value: "254" },
  { label: "ASSIMOCO VITA S.p.A.", value: "357" },
  { label: "ATHORA ITALIA S.p.A.", value: "213" },
  { label: "ATRADIUS CRÉDITO Y CAUCIÓN S.A. DE SEGUROS Y REASEGUROS", value: "816" },
  { label: "AVIVA LIFE & PENSIONS IRELAND DAC *", value: "670" },
  { label: "AWP P&C SA", value: "896" },
  { label: "AXA ASSICURAZIONI S.p.A.", value: "14" },
  { label: "AXA FRANCE IARD *", value: "653" },
  { label: "AXA FRANCE VIE *", value: "654" },
  { label: "AXA LIFE EUROPE DAC *", value: "875" },
  { label: "AXA MPS ASSICURAZIONI DANNI S.p.A.", value: "243" },
  { label: "AXA MPS ASSICURAZIONI VITA S.p.A.", value: "232" },
  { label: "AXERIA IARD SA *", value: "879" },
  { label: "AZIMUT LIFE DAC", value: "847" },
  { label: "BANCO BPM ASSICURAZIONI S.p.A.", value: "482" },
  { label: "BANCO BPM VITA S.p.A.", value: "402" },
  { label: "BCC ASSICURAZIONI S.p.A.", value: "418" },
  { label: "BCC VITA S.p.A. Compagnia di assicurazioni sulla vita *", value: "449" },
  { label: "BENE ASSICURAZIONI S.p.A. Società Benefit", value: "486" },
  { label: "BERKSHIRE HATHAWAY EUROPEAN INSURANCE DAC *", value: "665" },
  { label: "BERKSHIRE HATHAWAY INTERNATIONAL INSURANCE LIMITED *", value: "676" },
  { label: "BIM VITA S.p.A. *", value: "391" },
  { label: "BNP PARIBAS CARDIF VITA S.p.A.", value: "421" },
  { label: "CACI LIFE DAC *", value: "889" },
  { label: "CACI NON LIFE DAC", value: "890" },
  { label: "CARDIF ASSURANCE VIE SA *", value: "331" },
  { label: "CARDIF ASSURANCES RISQUES DIVERS SA *", value: "332" },
  { label: "CF ASSICURAZIONI S.p.A.", value: "464" },
  { label: "CF LIFE COMPAGNIA DI ASSICURAZIONI VITA S.p.A.", value: "361" },
  { label: "CG CAR-GARANTIE VERS.AKTIENGESELLSCHAFT *", value: "837" },
  { label: "CGPA EUROPE SA", value: "619" },
  { label: "CHUBB EUROPEAN GROUP SE", value: "853" },
  { label: "CHUBB LIFE EUROPE SE *", value: "878" },
  { label: "CIGNA LIFE INSURANCE CO. OF EUROPE *", value: "813" },
  { label: "CNA INSURANCE COMPANY (EUROPE) SA *", value: "659" },
  { label: "CNP ASSURANCES SA", value: "846" },
  { label: "CNP CAUTION SA *", value: "633" },
  { label: "CNP PARTNERS DE SEGUROS Y REASEGUROS SA *", value: "624" },
  { label: "CNP SANTANDER INSURANCE EUROPE DAC *", value: "603" },
  { label: "CNP SANTANDER INSURANCE LIFE DAC", value: "604" },
  { label: "CNP UNICREDIT VITA S.p.A.", value: "426" },
  { label: "CNP VITA ASSICURA S.p.A.", value: "339" },
  { label: "CNP VITA ASSICURAZIONE S.p.A.", value: "379" },
  { label: "COMP.FRANÇ.D'ASS.POUR LE COMMERCE EXTÉR.", value: "614" },
  { label: "COMPAGNIA ASSICURATRICE LINEAR S.p.A. *", value: "416" },
  { label: "CREDEMASSICURAZIONI S.p.A.", value: "428" },
  { label: "CREDEMVITA S.p.A.", value: "383" },
  { label: "CREDENDO - GUARANTEES & SPECIALITY RISKS *", value: "860" },
  { label: "CREDENDO - SHORT TERM NON-EU RISKS *", value: "622" },
  { label: "CRÉDIT AGRICOLE ASSICURAZIONI S.p.A.", value: "472" },
  { label: "CRÉDIT AGRICOLE VITA S.p.A.", value: "350" },
  { label: "D.A.S.", value: "142" },
  { label: "DARAG ITALIA S.p.A.", value: "293" },
  { label: "DOMESTIC & GENERAL INSURANCE EUROPE AG *", value: "668" },
  { label: "ELBA COMPAGNIA DI ASSICURAZIONE E RIASSICURAZIONI S.p.A.", value: "473" },
  { label: "ELIPS LIFE LIMITED", value: "637" },
  { label: "ERGO REISEVERSICHERUNG AKTIENGES. *", value: "876" },
  { label: "EULER HERMES S.A. N.V.", value: "606" },
  { label: "EURO INSURANCES DAC", value: "909" },
  { label: "EUROHERC OSIGURANJE D.D.", value: "971" },
  { label: "EUROP ASSISTANCE ITALIA S.p.A.", value: "390" },
  { label: "EUROVITA S.p.A.", value: "381" },
  { label: "FIDEURAM VITA S.p.A.", value: "479" },
  { label: "FM INSURANCE EUROPE SA *", value: "647" },
  { label: "FWU LIFE INSURANCE LUX SA", value: "868" },
  { label: "GARTENBAU VERSICHERUNG VVA *", value: "677" },
  { label: "GENERAL REINSURANCE", value: "821" },
  { label: "GENERALI ITALIA S.p.A.", value: "5" },
  { label: "GENERTEL S.p.A.", value: "247" },
  { label: "GENERTELLIFE S.p.A.", value: "445" },
  { label: "GLOBAL ASSISTANCE S.p.A.", value: "395" },
  { label: "GRAZER WECHSELSEITIGE VERSICHERUNG AG", value: "919" },
  { label: "GREAT LAKES INSURANCE SE", value: "899" },
  { label: "GREENVAL INSURANCE DAC", value: "964" },
  { label: "GROUPAMA ASSICURAZIONI S.p.A.", value: "151" },
  { label: "HARMONIE MUTUELLE *", value: "621" },
  { label: "HDI ASSICURAZIONI S.p.A.", value: "133" },
  { label: "HDI GLOBAL SE", value: "218" },
  { label: "HDI GLOBAL SPECIALTY SE *", value: "629" },
  { label: "HDI ITALIA S.p.A.", value: "86" },
  { label: "HELVETIA COMPAGNIA SVIZZERA D'ASSICURAZIONI", value: "19" },
  { label: "HELVETIA ITALIA ASSICURAZIONI S.p.A.", value: "292" },
  { label: "HELVETIA VITA S.p.A.", value: "448" },
  { label: "HOK OSIGURANJE D.D.", value: "962" },
  { label: "IMA ITALIA ASSISTANCE S.p.A.", value: "398" },
  { label: "INCONTRA ASSICURAZIONI S.p.A. *", value: "281" },
  { label: "INSURANCE JSC DALLBOGG LIFE AND HEALTH", value: "920" },
  { label: "INTER PARTNER ASSISTANCE SA", value: "399" },
  { label: "INTESA SANPAOLO ASSICURA S.p.A.", value: "419" },
  { label: "INTESA SANPAOLO LIFE DAC", value: "910" },
  { label: "INTESA SANPAOLO RBM SALUTE S.p.A.", value: "468" },
  { label: "INTESA SANPAOLO VITA S.p.A.", value: "306" },
  { label: "IPTIQ EMEA P&C SA", value: "671" },
  { label: "ITALIANA ASSICURAZIONI S.p.A.", value: "23" },
  { label: "ITAS VITA S.p.A.", value: "183" },
  { label: "ITAS-ISTITUTO TRENTINO ALTO ADIGE PER ASSICURAZIONI", value: "22" },
  { label: "LA MONDIALE EUROPARTNER S.A.", value: "810" },
  { label: "LE ASSICURAZIONI DI ROMA", value: "212" },
  { label: "LIBERTY MUTUAL INSURANCE EUROPE SE *", value: "608" },
  { label: "LLOYD'S INSURANCE COMPANY SA *", value: "656" },
  { label: "LOMBARD INTERNATIONAL ASSURANCE S.A. *", value: "627" },
  { label: "LONDON GENERAL INSURANCE COMPANY LTD *", value: "807" },
  { label: "MAPFRE ASISTENCIA - COMPANIA INT. DE SEGUROS Y REAS. SA", value: "844" },
  { label: "MAPFRE RE COMPANIA DE REASEGUROS SA *", value: "601" },
  { label: "MEDIOLANUM ASSICURAZIONI S.p.A.", value: "55" },
  { label: "MEDIOLANUM INTERNATIONAL LIFE DAC *", value: "841" },
  { label: "MEDIOLANUM VITA S.p.A.", value: "217" },
  { label: "METLIFE EUROPE DAC", value: "618" },
  { label: "METLIFE EUROPE INSURANCE DAC *", value: "617" },
  { label: "MMA IARD SA", value: "915" },
  { label: "MONUMENT ASSURANCE LUXEMBOURG SA", value: "829" },
  { label: "MSIG INSURANCE EUROPE AG *", value: "625" },
  { label: "MUNCHENER RUCKVERSICHERUNGS-GESELLSCHAFT", value: "882" },
  { label: "NET INSURANCE LIFE S.p.A.", value: "470" },
  { label: "NET INSURANCE S.p.A.", value: "441" },
  { label: "NOBIS COMPAGNIA DI ASSICURAZIONI S.p.A.", value: "474" },
  { label: "NOBIS VITA S.p.A.", value: "337" },
  { label: "OCTIUM ASSURANCE AG", value: "917" },
  { label: "OCTIUM ASSURANCE AG *", value: "854" },
  { label: "ONIX ASIGURARI SA *", value: "663" },
  { label: "OPTEVEN ASSURANCES SA *", value: "646" },
  { label: "POSTE ASSICURA S.p.A.", value: "480" },
  { label: "POSTE VITA S.p.A.", value: "431" },
  { label: "PRISMALIFE AG", value: "921" },
  { label: "PROBUS INSURANCE COMPANY EUROPE DAC", value: "906" },
  { label: "QBE EUROPE SA/NV *", value: "652" },
  { label: "QUIXA ASSICURAZIONI S.p.A.", value: "440" },
  { label: "R+V ALLGEMEINE VERSICHERUNG AG", value: "812" },
  { label: "REAL GARANT VERSICHERUNG AKTIENGESELLSCHAFT *", value: "649" },
  { label: "RGA INTERNATIONAL REINSURANCE COMPANY DAC", value: "887" },
  { label: "ROLAND RECHTSSCHUTZ VERSICHERUNG AG *", value: "867" },
  { label: "S.L.P. S.p.A. *", value: "226" },
  { label: "S2C S.p.A.", value: "481" },
  { label: "SACE BT S.p.A.", value: "455" },
  { label: "SARA ASSICURAZIONI S.p.A.", value: "32" },
  { label: "SARA VITA S.p.A.", value: "294" },
  { label: "SCOR SE", value: "874" },
  { label: "SCOTTISH WIDOWS EUROPE SA *", value: "664" },
  { label: "SI INSURANCE (EUROPE) SA", value: "655" },
  { label: "SIAT S.p.A. *", value: "175" },
  { label: "SOC. SVIZZERA D'ASSIC.CONTRO LA GRANDINE", value: "851" },
  { label: "SOCIETÀ CATTOLICA DI ASSICURAZIONE S.p.A.", value: "57" },
  { label: "SOCIETÀ REALE MUTUA DI ASSICURAZIONI S.p.A.", value: "35" },
  { label: "SOCIETE HOSPITALIERE D'ASSURANCES MUTUELLE (SHAM)", value: "634" },
  { label: "SOGECAP", value: "895" },
  { label: "SOGESSUR S.A.", value: "600" },
  { label: "STEWART TITLE EUROPE LIMITED *", value: "674" },
  { label: "SWISS RE EUROPE S.A.", value: "817" },
  { label: "SWISS RE INTERNATIONAL SE", value: "886" },
  { label: "TIROLER VERSICHERUNG VAG", value: "862" },
  { label: "TOKIO MARINE EUROPE SA *", value: "657" },
  { label: "TUA ASSICURAZIONI S.p.A.", value: "429" },
  { label: "TUTELA LEGALE S.p.A. *", value: "475" },
  { label: "UCA - ASSICURAZIONI SPESE LEGALI S.p.A. *", value: "127" },
  { label: "UNICREDIT ALLIANZ ASSICURAZIONI S.p.A.", value: "346" },
  { label: "UNICREDIT ALLIANZ VITA S.p.A. *", value: "415" },
  { label: "UNIPOLSAI ASSICURAZIONI S.p.A. *", value: "34" },
  { label: "UNIQA ÖSTERREICH VERSICHERUNGEN AG *", value: "828" },
  { label: "UNISALUTE S.p.A. *", value: "342" },
  { label: "USAA SA", value: "958" },
  { label: "VERA ASSICURAZIONI S.p.A.", value: "457" },
  { label: "VERA PROTEZIONE S.p.A. *", value: "477" },
  { label: "VERA VITA S.p.A. *", value: "437" },
  { label: "VEREINIGTE HAGELVERSICHERUNG VVAG", value: "849" },
  { label: "VERTI ASSICURAZIONI S.p.A.", value: "432" },
  { label: "VITTORIA ASSICURAZIONI S.p.A.", value: "38" },
  { label: "WAKAM", value: "955" },
  { label: "WEFOX INSURANCE AG", value: "922" },
  { label: "WIENER STÄDTISCHE VERS. AG VIENNA", value: "819" },
  { label: "XL INSURANCE COMPANY SE", value: "818" },
  { label: "XL RE EUROPE SE *", value: "678" },
  { label: "ZURICH INSURANCE COMPANY LIMITED", value: "198" },
  { label: "ZURICH INSURANCE PLC", value: "864" },
  { label: "ZURICH INVESTMENTS LIFE S.p.A.", value: "143" },
];
